/* config.h. Generated by cmake from config.h.cmake */

/* have TagLib */
#cmakedefine01 HAVE_TAGLIB

/* have Exiv2 */
#cmakedefine01 HAVE_EXIV2

/* Defined if we have libexiv2 >= 0.27 */
#cmakedefine01 HAVE_LIBEXIV2_0_27

/* have PoDoFo */
#cmakedefine01 HAVE_PODOFO

/* have KArchive */
#cmakedefine01 HAVE_KARCHIVE

/* have Freetype */
#cmakedefine01 HAVE_FREETYPE

#define VERSION "${krename_VERSION}"
