/* config.h. Generated by cmake from config.h.cmake */

/* have TagLib */
#define HAVE_TAGLIB ${HAVE_TAGLIB}

/* have Exiv2 */
#define HAVE_EXIV2 ${HAVE_EXIV2}

/* have PoDoFo */
#define HAVE_PODOFO ${HAVE_PODOFO}

/* have Freetype */
#define HAVE_FREETYPE ${HAVE_FREETYPE}

#define VERSION "${krename_VERSION}"
